<a href="https://colab.research.google.com/github/yshungria-uniandes/Data-Science-Fundamentals-/blob/main/Explorando_Arrays_con_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

x = np.array([1,5,3,8])
print(x)

[1 5 3 8]


In [5]:
x_list = [1,5,3,8]
print(x_list)

[1, 5, 3, 8]


In [8]:
# x_list + 3 No es compatible, mientras que en numpy si.

In [14]:
x + 3

array([ 4,  8,  6, 11])

In [16]:
x_ones = np.ones(4)
print(x_ones)

[1. 1. 1. 1.]


In [19]:
x_zeros = np.zeros(10)
print(x_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [27]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Creación de Arrays

**NumPy** proporciona varias formas de crear arrays. Exploraremos algunas de las más comunes.

**Arrays desde Listas:** Puedes crear un array de NumPy a partir de una lista de Python usando la función np.array

In [30]:
lista = [1, 2, 3, 4, 5]
array = np.array(lista)
print(array)

[1 2 3 4 5]


In [32]:
array_ceros = np.zeros(5)
print(array_ceros)

array_unos = np.ones((3, 4))
print(array_unos)

[0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
array_aleatorio = np.random.random(5)
print(array_aleatorio)

# Esto hace lo siguiente:

array_aleatorio_entero = np.random.randint(0, 10, size=(3, 3))
print(array_aleatorio_entero)

[0.71425972 0.78540489 0.61396446 0.77281579 0.14125252]
[[2 5 0]
 [5 0 7]
 [0 6 0]]


## Propiedades y Métodos de los Arrays

Una vez que tenemos arrays, es importante conocer sus propiedades y algunos métodos útiles para trabajar con ellos.

```
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.shape)
print(array.size)
print(array.ndim)

```

### Propiedades Básicas:

**Forma (shape):** Devuelve una tupla con las dimensiones del array.

**Tamaño (size):** Devuelve el número total de elementos en el array.

**Dimensión (ndim):** Devuelve el número de dimensiones del array.


### Métodos Útiles

**reshape:** Cambia la forma del array sin cambiar sus datos.

**flatten:** Convierte un array multidimensional en un array unidimensional.

In [38]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.shape)
print(array.size)
print(array.ndim)

(2, 3)
6
2


In [40]:
array_reshape = array.reshape((3, 2))
print(array_reshape)
#[[1 2]
# [3 4]
# [5 6]]
array_flatten = array.flatten()
print(array_flatten)
#[1 2 3 4 5 6]

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


## Operaciones Básicas con Arrays

NumPy permite realizar operaciones matemáticas básicas de manera eficiente.

In [43]:
#  Suma y Resta: Puedes sumar o restar arrays de la misma forma elemento por elemento.

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

suma = array1 + array2
resta = array1 - array2

print("Suma:", suma)
print("Resta:", resta)

#Suma: [5 7 9]
#Resta: [-3 -3 -3]



Suma: [5 7 9]
Resta: [-3 -3 -3]


In [45]:
# Multiplicación y División: La multiplicación y división también se realizan elemento por elemento.

multiplicacion = array1 * array2
division = array1 / array2

print("Multiplicación:", multiplicacion)
print("División:", division)

#Multiplicación: [ 4 10 18]
#División: [0.25 0.4  0.5 ]

Multiplicación: [ 4 10 18]
División: [0.25 0.4  0.5 ]


In [47]:
# Operaciones Universales (ufuncs): NumPy proporciona funciones universales (ufuncs) que realizan operaciones elemento por elemento.

array = np.array([1, 2, 3])

sqrt = np.sqrt(array)
log = np.log(array)

print("Raíz cuadrada:", sqrt)
print("Logaritmo natural:", log)

#Raíz cuadrada: [1.         1.41421356 1.73205081]
#Logaritmo natural: [0.         0.69314718 1.09861229]

Raíz cuadrada: [1.         1.41421356 1.73205081]
Logaritmo natural: [0.         0.69314718 1.09861229]


###  Indexación y Slicing de Arrays

La indexación y el slicing son técnicas para acceder a elementos específicos de un array.


In [49]:
# Indexación Básica:Puedes acceder a elementos individuales utilizando índices.

array = np.array([1, 2, 3, 4, 5])
print(array[0])  # Primer elemento
print(array[-1])  # Último elemento

# Slicing: Puedes acceder a subarrays utilizando la notación de slicing.
array = np.array([1, 2, 3, 4, 5])
print(array[1:4])  # Elementos del índice 1 al 3
print(array[:3])  # Primeros tres elementos
print(array[2:])  # Elementos desde el índice 2 hasta el final

#[2 3 4]
#[1 2 3]
#[3 4 5]

1
5
[2 3 4]
[1 2 3]
[3 4 5]


In [52]:
# Indexación y Slicing en Arrays Multidimensionales: La indexación y el slicing funcionan de manera similar en arrays multidimensionales.

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array)
print(array[1, 2])  # Elemento en la fila 1, columna 2
print(array[0:2, 1:3])  # Subarray desde fila 0 a 1 y columna 1 a 2

#6
#[[2 3]
#[5 6]]



[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[[2 3]
 [5 6]]


### Agregaciones y Estadísticas

NumPy proporciona funciones para realizar operaciones de agregación y calcular estadísticas básicas.

In [53]:
# Suma y Producto: Puedes calcular la suma y el producto de todos los elementos de un array.

array = np.array([1, 2, 3, 4, 5])

print(np.sum(array))  # Suma de todos los elementos
print(np.prod(array))  # Producto de todos los elementos

# 15
# 120

15
120


In [57]:
# Estadísticas Básicas: NumPy también proporciona funciones para calcular estadísticas básicas.

print(np.mean(array))  # Media (promedio)
print(np.median(array))  # Mediana
print(np.std(array))  # Desviación estándar
print(np.var(array))  # Varianza

# 3.0
# 3.0
# 1.4142135623730951
# 2.0


# # Resumen:

# Estas funciones son útiles para análisis de datos:

# Media (mean): Valor promedio.

# Mediana (median): Valor central.

# Desviación estándar (std): Mide la dispersión con respecto a la media.

# Varianza (var): Mide la dispersión al cuadrado.

# Usarlas en combinación ayuda a comprender mejor la distribución y variabilidad de los datos.


3.0
3.0
1.4142135623730951
2.0


In [59]:
# Agregaciones en Arrays Multidimensionales: Puedes realizar agregaciones a lo largo de un eje específico en arrays multidimensionales.

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array)
print(np.sum(array, axis=0))  # Suma a lo largo de las columnas

print(np.sum(array, axis=1))  # Suma a lo largo de las filas

# [12 15 18]
# [ 6 15 24]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]
